### ISSUE TITLE
Failure to load Nexus Files

### ISSUE THREAD

**Issue by JColes-Physics** [zjmorgan/rmc-discord#1]
I've only experienced this issue when trying to download rmc-discord onto computers other than the SNS analysis cluster. When I try to load my NeXus files which are exported directly from MANTID I get the error:

`AttributeError: 'Presenter' object has no attribute 'signal_raw_m'`

`AttributeError                            Traceback (most recent call last)`
`File ~/.local/lib/python3.9/site-packages/disorder/graphical/presenter.py:1993, in Presenter.load_data_complete(self)`
`   1991 def load_data_complete(self):`
`-> 1993     self.reset_data()`
`   1994     self.connect_experiment_buttons()`
`   1995     self.populate_recalculation_1d_table()`

`File ~/.local/lib/python3.9/site-packages/disorder/graphical/presenter.py:1643, in Presenter.reset_data(self)`
`   1639 self.view.block_experiment_table_signals()`
`   1641 self.view.clear_experiment_table()`
`-> 1643 self.signal_m = self.signal_raw_m.copy()`
`   1644 self.error_sq_m = self.error_sq_raw_m.copy()`
`   1646 nh, nk, nl = self.nh_raw_m, self.nk_raw_m, self.nl_raw_m`

`AttributeError: 'Presenter' object has no attribute 'signal_raw_m'`

A more detailed output is:

`File "/home/USER/.local/lib/python3.9/site-packages/disorder/graphical/utilities.py", line 79, in run
    result = self.fn(*self.args, **self.kwargs)`
`  File "/home/USER/.local/lib/python3.9/site-packages/disorder/graphical/presenter.py", line 1973, in load_data_thread
    h_range, k_range, l_range, nh, nk, nl = self.model.load_data(name)`
`  File "/home/USER/.local/lib/python3.9/site-packages/disorder/graphical/model.py", line 284, in load_data
    nh, nk, nl = experimental.data(fname)`
`  File "/home/USER/.local/lib/python3.9/site-packages/disorder/diffuse/experimental.py", line 28, in data
    Qh_min, Qk_min, Ql_min = Qh.min(), Qk.min(), Ql.min()`
`UnboundLocalError: local variable 'Qh' referenced before assignment`
`ERROR:root:Exception in GUI event loop`

I'm not sure if this is a known issue or not. I would just use the cluster to do this analysis but it seems the tutorial information at https://zjmorgan.github.io/rmc-discord/docs/tutorials/mno/index is a little out of date, and the script is no longer where it was.

**Comment by JColes-Physics** [comment]
Update: Upon further inspection the error comes from the pip installed version not being up to date. (I was unable to update for some reason) but after looking closer at this version of the program I just needed to set my axes names to (Q1,Q2,Q3) and it now works with my data. It was a simple fix in the end.
